### ISSUE TITLE
Problem with restarting simulation after error in summarise-function

### ISSUE THREAD

**Issue by jploetner** [philchalmers/SimDesign#11]
Hello Phil,

I encountered a possible bug or at least unintented behaviour of SimDesign. I was running a simulation with `save_results = TRUE` and everything was fine until I had an error in one condition in `Summarise` (because of a warning message, which was too long for a column name). I fixed that problem in `Analyse` and wanted to restart the simulation, but got the following error: 

> save_results_dirname not starting from correct location according to tempfile

I checked all my paths and the saved dirnames in the tempfile and everything was in order. Looking at the source code, the problem seems to be that after restarting a simulation it compares the first condition in the tempfile which is `NULL` (= `starts`) to the number of results saved in the folder `save_results_dirname ` and expects there to be one less file than `starts`, otherwise it throws the error from above. I fixed this problem by deleting the last results-file manually. Is there a way to handle this problem in SimDesign directly by catching that error with a specific error-message or ideally restarting the simulation by repeating the condition which lead to the error in `Summarise`.

I included a small example:

    library(SimDesign)
    
    Design <- data.frame(m = 1:4)
    
    Generate <- function(condition, fixed_objects = NULL) {
      dat <- data.frame(x = rnorm(100, condition$m, 1))
    }
    
    Analyse <- function(condition, dat, fixed_objects = NULL) {
      error <- 0
      if(condition$m == 3) error <- 1 # exclude this line after first run
      res <- c(m = mean(dat$x), error = error)
    }
    
    Summarise <- function(condition, results, fixed_objects = NULL) {
      if(any(results[, "error"] == 1)) {
        stop("ERROR")
      }
    
      res <- c(m = mean(results[, "m"]))
    }
    
    results <- runSimulation(design=Design, replications=5, 
                             generate=Generate, analyse=Analyse, summarise=Summarise,
                             progress = TRUE, max_errors = 5,
                             save = TRUE, save_results = TRUE,
                             save_details = list(save_results_dirname = "SimResults")
    )

**Comment by philchalmers** [comment]
Thanks for the report and code to work with!

It seems this is one of the very few times where I'm okay with over-writing previously saved data. If it turns out the `summarise()` was the reason that the error was thrown, which seems to be the case here, then allowing the last .rds file to be overwritten makes sense since the `analyse()` results could have actually been the culprit creating this issue down the line. The fix now allows for this. Thanks again! And let me know if this fix doesn't address your main simulation's issue.
