### ISSUE TITLE
Error with `reSummarise()` with `bootSE = TRUE`

### ISSUE THREAD

**Issue by marklhc** [philchalmers/SimDesign#15]
Hi Phil,

I got this error when running `reSummarise()` with `bootSE = TRUE`:

```
Error in as.integer(max) : 
  cannot coerce type 'closure' to vector of type 'integer'
```

Because inside the function it has this part:

```r
      SE_sim_results <- sapply(1L:boot_draws, function(r) {
        pick <- rint(n = replications, min = 1L, max = replications)
        tmp <- if (!is.data.frame(inp$results)) 
          inp$results[pick]
        else inp$results[pick, , drop = FALSE]
        summarise(results = tmp, condition = inp$condition, 
          fixed_objects = fixed_objects)
      })
```

but `replications` is not defined or extracted from the saved results.

Best,

Mark

**Comment by philchalmers** [comment]
Great, thanks for the report. It looks like there also were no unit tests for `reSummarise()` for some reason, so I've now included tests to help avoid this function breaking in future releases.
