### ISSUE TITLE
Code in SimDesign Package Won't Run for window 10!!

### ISSUE THREAD

**Issue by InnocentSky** [philchalmers/SimDesign#22]
install.packages("simdesign")
Installing package into ‘C:/Users/HP/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘simdesign’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  Perhaps you meant ‘SimDesign’ ?

**Comment by philchalmers** [comment]
R is case sensitive; 'simdesign' != 'SimDesign'.
