### ISSUE TITLE
Question / Issue

### ISSUE THREAD

**Issue by jgman86** [philchalmers/SimDesign#24]
Hello Phil,

I hope this message finds you well.

I've been utilizing `simDesign` to execute a substantial MCMC Simulation, encompassing over 200,000 models. To systematically track the individual outcomes, I initially stored all results from the `analyse` function into an `.RDS` file. The filename encapsulates both the condition and the model. For instance, within the `summarise` function, I've employed the following approach:

`   Analyze_M3(){

    ..........
    # max rhat for subject theta
    
    max_rhat_c <- subj %>% select(contains("rhat_c")) %>% max()
    max_rhat_a <- subj %>% select(contains("rhat_a")) %>% max()
    
    # Predictive Correlation for Different Response Categories
    
    cor_rep_IIP <- cor(dat[[3]][,"IIP"],count_rep$IIP)
    cor_rep_IOP <- cor(dat[[3]][,"IOP"],count_rep$IOP)
    cor_rep_NPL <- cor(dat[[3]][,"NPL"],count_rep$NPL)
    
    
    # Merge Results for current iteration
    
    ret <- data.frame(re_c = recoveries_c,
                      rmse_c = rmse_c,
                      rmse_mu_c=rmse_mu_c,
                      rhat_c = max_rhat_c,
                      
                      re_a=recoveries_a,
                      rmse_a = rmse_a,
                      rmse_mu_a=rmse_mu_a,
                      rhat_a=max_rhat_a,
                      
                      cor_rep_IIP = cor_rep_IIP,
                      cor_rep_IOP = cor_rep_IOP,
                      cor_rep_NPL = cor_rep_NPL)
    
    ret <- cbind(condition, ret)

    .....rest of the code }`

```
Summarise_M3 <- function(condition,results,fixed_objects=NULL) {
  
  Attach(condition)
  
  
  # Load Model Type 
  
  # Create the base model name
  model_name <- paste0("M3_", model_type)
  
  # Check if the 'fixed' condition applies
  if (!(model_type == "SS" || model_type == "CS")) {
    if (fixed == 1) {
      # Append '_fixed' to the model name
      model <- paste0(model_name, "_fixed")
    } else {
      model <- model_name
    }
  } else {
    model <- model_name
  }
  

  
  # Create filename according to condition
  # 
  # if (!(model == "M3_SS" || model == "M3_CS")) {
  #   
  #   file.name <- paste0("Con.",model,".","N.",OtherItems,".","K.",NPL,
  #                       ".","nRet.",Retrievals,".",
  #                       "nFT.",nFreetime,".","length_FT.",length_FT,
  #                       ".fixed.", fixed, ".RDS")
  # } else {
  #   
  #   file.name <- paste0("Con.",model,".","N.",OtherItems,".","K.",NPL,
  #                       ".","nRet.",Retrievals,".RDS")
  #   
  # }
  # 
  # 
  # 
  # saveRDS(results, paste0(fixed_objects$output.dir.reps,file.name))
  
  if(model== "M3_CS_EE"){
    
    ..... rest of code.....

```

Error:

```

Design row: 1/1;   RAM used: 157.1 Mb;   Total elapsed time: 0.00s 
 Conditions: REPLICATION=0, OtherItems=5, NPL=8, Retrievals=500, model_type=CS
New names:
• `ID` -> `ID...1`
• `REPLICATION` -> `REPLICATION...2`
• `OtherItems` -> `OtherItems...3`
• `NPL` -> `NPL...4`
• `Retrievals` -> `Retrievals...5`
• `model_type` -> `model_type...6`
• `ID` -> `ID...7`
• `REPLICATION` -> `REPLICATION...8`
• `OtherItems` -> `OtherItems...9`
• `NPL` -> `NPL...10`
• `Retrievals` -> `Retrievals...11`
• `model_type` -> `model_type...12`
Error in `dplyr::as_tibble()`:
! Column names `REPLICATION`, `OtherItems`, `NPL`, `Retrievals`, and
  `model_type` must not be duplicated.
Use `.name_repair` to specify repair.
Caused by error in `repaired_names()`:
! Names must be unique.
✖ These names are duplicated:
  * "REPLICATION" at locations 1 and 7.
  * "OtherItems" at locations 2 and 8.
  * "NPL" at locations 3 and 9.
  * "Retrievals" at locations 4 and 10.
  * "model_type" at locations 5 and 11.
Backtrace:
     ▆
  1. └─SimDesign::runSimulation(...)
  2.   ├─dplyr::as_tibble(stored_Results_list)
  3.   └─tibble:::as_tibble.data.frame(stored_Results_list)
  4.     └─tibble:::lst_to_tibble(unclass(x), .rows, .name_repair)
  5.       └─tibble:::set_repaired_names(...)
  6.         └─tibble:::repaired_names(...)
  7.           ├─tibble:::subclass_name_repair_errors(...)
  8.           │ └─base::withCallingHandlers(...)
  9.           └─vctrs::vec_as_names(...)
 10.             └─vctrs (local) `<fn>`()
 11.               └─vctrs:::validate_unique(names = names, arg = arg, call = call)
 12.                 └─vctrs:::stop_names_must_be_unique(names, arg, call = call)
 13.                   └─vctrs:::stop_names(...)
 14.                     └─vctrs:::stop_vctrs(...)
 15.                       └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = call)
Execution halted
```

Interestingly, this setup runs seamlessly on my home system, saving a dataframe (not a list) to a designated "conditions" folder with the specified filename and all pertinent condition information. However, when executed on the HPC, I encounter an error related to duplicated columns in the summary file, which is a `dplyr` error. I surmise this might be due to the combination process in the preceding function. Could this be attributed to a version-specific change? It's worth noting that everything operates as expected on my home setup.

On further exploration, I discerned that it's feasible to store the intermediate results from the `analyse` function directly, eliminating the need for an additional saving routine:

```R
 save = FALSE, save_results = TRUE,
              save_details = list(out_rootdir=paste0(default.out,"Results/",model_type,"/"),
                                  save_results_dirname=paste0("Conditions/")),
```

This method yields the desired results without any errors. However, there's a minor hiccup with the naming convention. Given that I parallelize all simulation conditions simultaneously, with each HPC node handling a single condition, the resultant folder is simply named "_1" and the file is labeled "results-row-1". I'm concerned this might lead to complications, especially when running multiple simulations across different nodes, as I intend for the results to be consolidated within a single directory. Is there a way to modify the naming to reflect the simulation condition?

Thank you for your time and assistance. I appreciate your expertise on this matter.

Warm regards,

Jan

**Comment by philchalmers** [comment]
Hi Jan,

> Could this be attributed to a version-specific change? It's worth noting that everything operates as expected on my home setup.

That is my first suspicion as I have had to modify a few of the internal objects to allow more flexible storage properties. Apologies if this is what is breaking your code, though I believe the changes are the most optimal moving forward. 

> On further exploration, I discerned that it's feasible to store the intermediate results from the analyse function directly, eliminating the need for an additional saving routine:

I can see this as being a problem for sure, particularly because the files are not checked for their uniqueness before saving. That's something I'll add to the next version so that such an issue is avoidable and valuable computing time is not lost. 

In your case for now, it may be better to supply unique `dirname`s that are associated with the `Design` row identifies (even just the row number). Alternately, if you HPC RAM is not a huge issue or your analysis results are not overly large, you can use the `store_results = TRUE` flag to store the results internally rather than writing them do the drive. They could then be extracted after the fact on an object-by-object basis. HTH.

**Comment by jgman86** [comment]
Hi Phil, 

yes I did this and supplied the unique dirnames, which works as expected. However, because it now generates 10k - 60k folders with one file each, the saving feature would be - for larger simulations which are heavily parallelized to one row per job - a big W. 

Another feature I was thinking about was the support for the h5 - fileformat for the saving routine. In my case, I'm saving all information in an .RDS file at the end of the analyse function - including the draws of the MCMC fitting (10 - 30 MB per file). For such a huge amount of small files, the I/O process takes a lot of time and ressources (RAM is insufficient on normal machines), because it is only possible to read in the whole file, including also large objects within the list (e.g. the draws).

A big advantage of the h5-file system ([Link](https://www.bioconductor.org/packages/devel/bioc/vignettes/rhdf5/inst/doc/rhdf5.html))
is that it is possible to directly read desired data from the file, without the need of further processing operations (e.g. loop over all data to read in, save the desired objects from the list on each iteration of the loop).  It has a hierachical (file-system like) architecture. For SimDesign this would allow to store all information of a simulation in a single file with an hieracichal structure like this:

```
##         group   name       otype   dclass       dim
## 0           /    SimGenerate   H5I_GROUP                   
## 1        /SimGenerate/     df_gen H5I_DATASET COMPOUND         5
## 2           /    SimAnalyse   H5I_GROUP                   
## 3        /SimAnalyse      df_ResultsA H5I_DATASET  FLOAT   100 x 20
## 4        /SimAnalyse      df_ResultsB H5I_DATASET  FLOAT  100 x 10
## 5         / simSummarise               
## 6      /simSummarise/    SummariseObjects H5I_DATASET   FLOAT  10 x 10
```

In the context of simulation, this seems to be a pretty nice feature ! Thanks for your support !

**Comment by philchalmers** [comment]
The h5 approach seems interesting, but I worry it may be overkill for most users. Of course, if you are looping over each simulation condition independently then nothing really stops you from implementing your own h5 structure to store the object information directly (the `store_results = TRUE` approach). 

w.r.t. this issue it might be easiest to allow the filenames to be better exposed to the user so at least you have control over the naming structures, as I agree so many folders containing one file is completely unnecessary.

**Comment by philchalmers** [comment]
I've allowed for a new `save_results_filename` to be supplied which disables the save checks for directory storage uniqueness, thereby allowing all files to be stored to the same specified directory asynchronously. That should solve your issue so long as you pass a unique  `save_results_filename` argument for each row condition. Note that file names are not checked with this approach, so the unique names will fall on user side. Feel free to reopen if there are issues, and thanks for the report!

**Comment by jgman86** [comment]
That's awsome ! I think this is really W !
