### ISSUE TITLE
Variable naming error when using `runSimulation()`

### ISSUE THREAD

**Issue by bsiepe** [philchalmers/SimDesign#26]
Hello,

thank you for creating this amazing package!

I am using `SimDesign` for a simulation study with a package that is work-in-progress, making a fully reproducible example complicated at this point. I fully understand if you are unable to help me without one, and I realize that the underlying issue may not be within your package.

The simulation involves four different analysis strategies for time-series structural equation models, where each simulated individual has a unique data-generating process embedded within a larger group-model. This results in a list of data-generating parameters and estimates passed along the analysis pathway. The `summarise` function returns a list containing four named vectors, each containing performance measures for a specific analysis function.

In a working condition, this is the output of the `SimExtract(., what = "summarise")` function:
```
list(`n_ind=30 ; ar=0.2 ; ind_a=0.15 ; ind_phi=0.05` = 
list(
default = c(ari_m = -0.0041, prec_dir_m = 0.14119, recall_dir_m = 0.14119), 
liberal = c(ari_m = -0.0041, prec_dir_m = 0.15279, recall_dir_m = 0.15279), 
strict = c(ari_m = -0.0041, prec_dir_m = 0.13942, recall_dir_m = 0.13942), 
threshold1 = c(ari_m = -0.0041, prec_dir_m = 0.14549, recall_dir_m = 0.14549)))
```

The problem arises when I change the sample size in my data generation to a larger number, which generates more individual models. When running `runSimulation()`, an error occurs with the following message:

```
Error in do.call(data.frame, c(x, alis)) : 
  variable names are limited to 10000 bytes

5: do.call(data.frame, c(x, alis))
4: as.data.frame.list(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
3: as.data.frame(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
2: data.frame(design[i, ], as.list(tmp), check.names = FALSE)
1: SimDesign::runSimulation(sim_design_test, replications = replications, 
       generate = sim_generate, analyse = sim_analyse_all, 
       summarise = sim_summarize, packages = c("mvgimme", "here"), 
       fixed_objects = sim_pars, parallel = TRUE)
```
It seems likely to me that some larger object is somewhere saved as a name. I have used `browser()` to debug all three simulation functions and found no apparent structural differences between the conditions that work and those that throw an error. There are also no issues with nonconvergence, and the output of `summarise` does not depend on the sample size. 

I have tried the following without success:
- Using a list of analysis functions vs. one analysis function containing multiple analyses
- Returning a list of results vs. a named vector of results for `summarise`
- shortening the names and reducing the number of performance measures in `summarise`
- not using a `summarise` function at all
- turning the various save options in `SimDesign` on or off

I would greatly appreciate any help or intuition about this problem.

Thanks,
Björn

**Comment by philchalmers** [comment]
I should mention, this doesn't have to be your actual simulation. Just a stub for generate-analyse combination is fine, though emulating the behaviour of the very long summarise() list output should be sufficient to reproduce the issue.

**Comment by bsiepe** [comment]
Thank you for the fast response and your offer to help! I will e-mail you a reprex within the week.

**Comment by philchalmers** [comment]
Thanks for the reprex. Looks like the issue was related to very long `warning` strings being caught and coerced to names. The package now clips error/warning message names to 150 characters to avoid such issues but still allow the tallying of these issues in the output.

**Comment by bsiepe** [comment]
Great, thank you for the fast fix!
