### ISSUE TITLE
aggregate_simulations and summary results

### ISSUE THREAD

**Issue by mronkko** [philchalmers/SimDesign#35]
`aggregate_simulations` works currently by aggregating all results from many results files. This may not work well with very large simulations. For example, I have a simulation that produced around 300GB of replication data. (In this case, computation was expensive, and therefore, it made sense to save a lot of different statistics from each replication.) Loading these results with `aggregate_simulations` would not work because the computer runs out of memory. 

I also propose adding `aggregate_simulations_summaries`  function, which would run the `summarise` function from dplyr to each design before aggregating the results.  This would allow aggregating the simulation results as summary statistics instead of raw statistics considerably reducing the memory requirements.

**Comment by philchalmers** [comment]
I'm not quite sure I follow this. Could you elaborate?

**Comment by mronkko** [comment]
Yes. Let's assume we have a very large simulation with 10 000 designs. This is run so that that each desing is a separate R data file of 30MB consisting of 1000 replications of various statistics producing 300GB of simulation data.

The normal workflow for analyzing a simulation would involve 1) Aggregate all simulation results into a tibble and 2) calculating summary statistics from the tibble, typically by design or groups of designs. With very large simulations this not feasible because of the memory requirements. I propose adding support for a reverse workflow: 1) Calculate summary statistics for each design and 2) aggregate the summary statistics into a tibble. 

Does this make sense?

**Comment by philchalmers** [comment]
Yes. Though from what I can tell this is already possible by way of the `reSummarise()` function and using the `files` argument. If you were to point to a subset of the stored `files` to be read in then one design and summarised results are available in isolation, at which point further marginalization could occur to further collapse this information however you'd like. This would then be tacked onto to the next batch of files, which is again read in, marginalized, and now glued/rbind onto the first batch of marginalized information, thereby building up the marginalized design pieces independently. Rinse and repeat for all other file subsets.

Automating this process would require a large number of assumptions before constructing a workable `aggregate_simulations_summaries()` function as there's no guarantee that the stored information is even homogenous across simulations (e.g., if you're storing factor loadings in design one with J=20 indicators, but in the second stored design you studied J=30 indicators, how would the function know what to combine?). This feels to be an area where the responsibility falls on the front-end user to manage the extraction, marginalization, and building of the resulting objects.

**Comment by mronkko** [comment]
Yes, `reSummarise()` seems to be at least very close to what I would like to have. If this supported selective loading of results  (#34) it would probably solve my summarization needs.

**Comment by philchalmers** [comment]
This should work now with greater subset specificity. Thanks for bringing this to my attention.
