### ISSUE TITLE
check design dataset on resume

### ISSUE THREAD

**Issue by TobiasFellinger** [philchalmers/SimDesign#39]
If a folder contains a tempfile from simulations with different parameter-sets the simulation is restarted with the new parameter-set starting from the last line number contained in the old file. The output file is concatenated, if the parameter-sets contained different columns, the columns are NA before and after the respective line number. 

Please add a check and do not resume simulations for a different design dataset but instead stop with an informative error-message.

**Comment by philchalmers** [comment]
I don't quite follow. The NA placeholders are included given that different conditions (rows in `design`) can result in very different outputs, so this seems as a feature not a bug. Could you provide a brief reprex demonstrating the issue you're encountering?

**Comment by TobiasFellinger** [comment]
Thank you for your quick response. The NA placeholders are indeed reasonable and a very useful feature. 

The case where I encountered this is the following: I ran simulations in scenario classes using different data generating mechanisms but evaluating the same analysis methods. So `Design` and `Generate` were different, `Design` having different columns. `Analyse` and `Summarise` were the same for both scripts. 

There may be cases in which resuming simulations for a changed `Design` and `Generate` objects, but I think not resuming in this case would be a more reasonable and safer default behaviour.

```
library(SimNPH)

Design_1 <- data.frame(
  fail = c(0, 1, 0)
)

Generate_1 <- function(condition, fixed_objects = NULL) {
  if(condition$fail == 1){
    q(save="no", status=-1)
  } else {
    return(data.frame(x=1))
  }
}

Analyse_1 <- function(condition, dat, fixed_objects = NULL) {
  ret <- nc(x=dat$x)
  ret
}

Summarise_1 <- function(condition, results, fixed_objects = NULL) {
  ret <- c(meanx=mean(results$x))
  ret
}

res <- runSimulation(
  design=Design_1,
  replications=1000,
  generate=Generate_1, 
  analyse=Analyse_1, 
  summarise=Summarise_1,
  resume = TRUE
)

# -------------------------------------------------------------------------
# Here the R-session quits, a tempfile is left in the working directory
# 
# After starting a new R-session and switching to the previous working directory
# continue here
# -------------------------------------------------------------------------

library(SimNPH)

Design_2 <- data.frame(
  different_parameter = c(0, 1, 0)
)

Generate_2 <- function(condition, fixed_objects = NULL) {
  return(data.frame(x=condition$different_parameter))
}

# not necessarily the same
Analyse_1 <- function(condition, dat, fixed_objects = NULL) {
  ret <- nc(x=dat$x)
  ret
}

# not necessarily the same
Summarise_1 <- function(condition, results, fixed_objects = NULL) {
  ret <- c(meanx=mean(results$x))
  ret
}

res <- runSimulation(
  design=Design_2,
  replications=1000,
  generate=Generate_2, 
  analyse=Analyse_1, 
  summarise=Summarise_1,
  resume = TRUE
)
```

Possible implementation: one could store a checksum of the `Design` (and possibly the `Generate`) object in the tempfile (something like the output of `digest::digest`) and compare to the value for the current `Design` object before resuming.

**Comment by philchalmers** [comment]
Above example now generates the following on the resume call:

```r
Resuming simulation from ./SIMDESIGN-TEMPFILE_HOME.rds file. 
If not intended, use SimClean() prior to calling runSimulation()
Error: design names are not the same upon resuming simulation.
```

**Comment by TobiasFellinger** [comment]
Thank you for the quick implementation. Yes this is definitely avoidable if one cleanly separates testing and implementation and testing phases. But the additional check is definitely helpful and helps to catch errors before inspecting the results.
