### ISSUE TITLE
Paste filename instead of indexing string?

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#44]
https://github.com/philchalmers/SimDesign/blob/f69e47756c11959b5ef1082079f1fb8c8f0d8f76/R/runArraySimulation.R#L354

Not to file too many issues, but while I was reading the code--should this be something like `paste0(filename, [i])` instead of `filename[i]`? I can't run it in a debugger, but I imagine so?

I mean, this doesn't produces anything seemingly useful? `gsub("//", "/", file.path(getwd(), "test.rds"))[2]`

**Comment by philchalmers** [comment]
This is a unique filename check so in general it doesn't modify the filename[i] term unless the same filename already exists. The pasting() happens earlier in the codebase. 

I think this is a false positive, so I'll close, but feel free to reopen if you think this is somehow a problem.
