### ISSUE TITLE
Bug/Documentation Note on Running External Executables?

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#46]
The `max_time` argument is a great feature. But, sometimes when certain computations have a somewhat unpredictable run time, such as Hamiltonian Monte Carlo, it seems like SimDesign can fail to halt the replication and safely exit with whatever progress has been made. 

Would it be possible for SimDesign to kick-off a temporary file of whatever has been completed once the 'max_time' is met, or perhaps documentation be updated to consider putting a `max_time` that's even smaller than the 90-95% recommended [here](https://cran.r-project.org/web/packages/SimDesign/vignettes/HPC-computing.html) when runtimes are unpredictable?

**Comment by philchalmers** [comment]
The completed replications prior to `max_time` should be stored, though this is risky behaviour given the R interpreter. Ideally there would be a sentinel overviewing the simulation and once the exact `max_time` has been reached the simulation terminates and whatever has been completed is returned. Unfortunately, I know of no such way of doing this in R, though it may be possible to configure a daemon outside of R to make these checks and send a kind of termination signal to the R process. I'd have to ask around if such a thing is even possible....

**Comment by philchalmers** [comment]
To your point though, yes using a much smaller max time for unpredictable simulations can work, but it doesn't really fix the nature of the issue. The only sure-fire way around this would be to distribute each replication to an independent computing enviroment and, if it fails within the allotted script time to the cluster, then you'd know how and what to repeat. I imagine for MCMC type simulations this may be the best and only workable strategy.

**Comment by philchalmers** [comment]
*Addendum* I should have noted in the documents that the timeout features are not fool proof. It generally works well for R code so long as the individual functions being called are effectively trivial, but in situations where something like `.Call()` is used for C/C++ code the interpreter has to wait for these calls to finish and, AFAIK, will not interrupt to binary code being processed. This is likely where you issue is with the `stan` process as something living entirely within a C++ program doesn't let the R interpreter interrupt the program (this would have to be baked into the C++ code itself). Hope that clarifies the issue.

**Comment by emstruong** [comment]
> The completed replications prior to `max_time` should be stored, though this is risky behaviour given the R interpreter. Ideally there would be a sentinel overviewing the simulation and once the exact `max_time` has been reached the simulation terminates and whatever has been completed is returned. Unfortunately, I know of no such way of doing this in R, though it may be possible to configure a daemon outside of R to make these checks and send a kind of termination signal to the R process. I'd have to ask around if such a thing is even possible....

Isn't this only for `runSimulation` and not `runArraySimulation` though? `runSimulation` sets `save` to `FALSE`, so I don't think it works for `runArraySimulation`?

**Comment by emstruong** [comment]
> _Addendum_ I should have noted in the documents that the timeout features are not fool proof. It generally works well for R code so long as the individual functions being called are effectively trivial, but in situations where something like `.Call()` is used for C/C++ code the interpreter has to wait for these calls to finish and, AFAIK, will not interrupt to binary code being processed. This is likely where you issue is with the `stan` process as something living entirely within a C++ program doesn't let the R interpreter interrupt the program (e.g., [here](https://github.com/philchalmers/SimDesign/blob/2c784c63404e353dc9042f07c5407fbb1dd5e362/R/util.R#L400)). Hence, this would have to be baked into the C++ code itself, so would fall on the developers of the stand-alone binary programs. Hope that clarifies the issue.

Would the external daemon solution work here?

I don't know much about the parallel processing options in R, but I was hoping that there would an easy way to kill the processes running their code past the `max_time`--while not really messing with everything else. 

Although, somehow, based on my informal experience using the `futureverse` associated libraries to actually analyze all this data, things are never easy when it comes to parallel processing...

**Comment by philchalmers** [comment]
> > The completed replications prior to `max_time` should be stored, though this is risky behaviour given the R interpreter. Ideally there would be a sentinel overviewing the simulation and once the exact `max_time` has been reached the simulation terminates and whatever has been completed is returned. Unfortunately, I know of no such way of doing this in R, though it may be possible to configure a daemon outside of R to make these checks and send a kind of termination signal to the R process. I'd have to ask around if such a thing is even possible....
> 
> Isn't this only for `runSimulation` and not `runArraySimulation` though? `runSimulation` sets `save` to `FALSE`, so I don't think it works for `runArraySimulation`?

... You may be right here, though not this has less to do with the `save` input. The time should be defined within `runSimulation()` as the delta and `runArraySimulation()` as the overall. I'll look into this as from what I can tell the `max_time` is applied per condition, which is fine, but should be adjusted if the intention is across the entire array job. Thanks for looking into that.

**Comment by philchalmers** [comment]
> > _Addendum_ I should have noted in the documents that the timeout features are not fool proof. It generally works well for R code so long as the individual functions being called are effectively trivial, but in situations where something like `.Call()` is used for C/C++ code the interpreter has to wait for these calls to finish and, AFAIK, will not interrupt to binary code being processed. This is likely where you issue is with the `stan` process as something living entirely within a C++ program doesn't let the R interpreter interrupt the program (e.g., [here](https://github.com/philchalmers/SimDesign/blob/2c784c63404e353dc9042f07c5407fbb1dd5e362/R/util.R#L400)). Hence, this would have to be baked into the C++ code itself, so would fall on the developers of the stand-alone binary programs. Hope that clarifies the issue.
> 
> Would the external daemon solution work here?

In principle, yes, but you'd need to send the signal to the main R process to terminate the 'slaves'. And that would be a little tricky to configure on something like SLURM without some admin help.

> 
> I don't know much about the parallel processing options in R, but I was hoping that there would an easy way to kill the processes running their code past the `max_time`--while not really messing with everything else.
> 
> Although, somehow, based on my informal experience using the `futureverse` associated libraries to actually analyze all this data, things are never easy when it comes to parallel processing...

The `max_time` type of idea would be applied to each spawned process, which is what makes it so difficult to work with as the spawns do not talk to each other (so each `max_time` would have to be distributed as a meaningful fraction.... which is a problem in and of itself!). I don't think you'll find this kind of feature in something like `tidyverse` as it's a rather specific problem related to HPCs.

**Comment by emstruong** [comment]
> ... You may be right here, though not this has less to do with the `save` input. The time should be defined within `runSimulation()` as the delta and `runArraySimulation()` as the overall. I'll look into this as from what I can tell the `max_time` is applied per condition, which is fine, but should be adjusted if the intention is across the entire array job. Thanks for looking into that.

Yeah... runArraySimulation is more than a wrapper... :sweat_smile: 

IMO some of the functionality in runArraySimulation should be shifted over to the other internal functions that way the switch from `runSimulation` to `runArraySimulation` really minimizes breakage. It's the breakage once you switch from `runSimulation` to `runArraySimulation` that makes the output messages and etc really helpful too... But that's a different story

https://github.com/philchalmers/SimDesign/blob/2c784c63404e353dc9042f07c5407fbb1dd5e362/R/runArraySimulation.R#L301-L305

https://github.com/philchalmers/SimDesign/blob/2c784c63404e353dc9042f07c5407fbb1dd5e362/R/runArraySimulation.R#L346-L349

Those are the lines that I'm referring to when I say `save` is forced to `FALSE` in `runSimulation` within the context of `runArraySimulation`. 

---

By the way, does `runArraySimulation` not support `future(verse)` stuff? I thought `runSimulation` did?

**Comment by emstruong** [comment]
> The `max_time` type of idea would be applied to each spawned process, which is what makes it so difficult to work with as the spawns do not talk to each other (so each `max_time` would have to be distributed as a meaningful fraction.... which is a problem in and of itself!). I don't think you'll find this kind of feature in something like `tidyverse` as it's a rather specific problem related to HPCs.

Oh... I think we may have talked past each other--but well I was digressing. And I'll digress even more by saying, look at this! https://furrr.futureverse.org/articles/gotchas.html It's such a list of gotchas... It's something you can get used to, but it's quite the restrictions...

**Comment by philchalmers** [comment]
> > The `max_time` type of idea would be applied to each spawned process, which is what makes it so difficult to work with as the spawns do not talk to each other (so each `max_time` would have to be distributed as a meaningful fraction.... which is a problem in and of itself!). I don't think you'll find this kind of feature in something like `tidyverse` as it's a rather specific problem related to HPCs.
> 
> Oh... I think we may have talked past each other--but well I was digressing. And I'll digress even more by saying, look at this! https://furrr.futureverse.org/articles/gotchas.html It's such a list of gotchas... It's something you can get used to, but it's quite the restrictions...

Here's one more gotcha in this context; `futureverse` doesn't work with HPC array distributions. So yes, it works with `runSimulation()`, but not the newer array wrapper.

**Comment by emstruong** [comment]
> Here's one more gotcha in this context; `futureverse` doesn't work with HPC array distributions. So yes, it works with `runSimulation()`, but not the newer array wrapper.

Okay, interesting... Why's that? 

I was under the impression that what makes `runArraySimulation` so easy is because it's essentially just managing `runSimulation`, but with controls on where files are outputted and what conditions are run based on `ArrayID`, no? Why would that affect whether `futureverse` works or not?

Like, I was under the impression that if I set `arrayID = 1` and ran `runArraySimulation` (maybe with some other small things) that the computation should be 1 to 1 with `runSimulation`, no?

**Comment by emstruong** [comment]
Well, I think this is mostly it -- but would it be possible to toggle the `save` argument through `runArraySimulation()` or is that no good?
