### ISSUE TITLE
Allow Passing List of Files with Directories to SimCollect?

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#47]
https://github.com/philchalmers/SimDesign/blob/6b8fc6ee6c425f86349c4f4b53f12be0f19946e0/R/SimCollect.R#L148-L157

If files are located in a sub-directory other than the working directory, then line 156 will add an unneeded `./` when using `SimCollect(files = list.files(path = ..., pattern = "*.rds", full.names = TRUE))`

Perhaps allow setting both `dirs` and `files`, or an easier way of using the two together?

**Comment by philchalmers** [comment]
Not sure why you wouldn't just specify the directory path explicitly as all .rds files should be in a self-contained folder, but sure there's no harm in patching this as it could be useful if you're trying to collect only a subset of the files for checking purposes.

**Comment by emstruong** [comment]
It's because I did a silly thing and put other folders in the folder where the `.rds` files are... But yes, it'd be appreciated if I could just manually feed it the list of filenames + directories

**Comment by philchalmers** [comment]
Should be closed with #48, you can see an example added to show that it works.

**Comment by emstruong** [comment]
Although #48 seems to be solved in the latest commit, I suspect that there is some sort of regression in what files are read in. 

![image](https://github.com/user-attachments/assets/20bb9203-1377-4851-8a53-691877906efd)

**Comment by emstruong** [comment]
hold-on, I must've done something wrong. Let me manually debug then get back to you...
