### ISSUE TITLE
High RAM Usage in SimCollect Even When Only Selecting REPLICATIONS

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#48]
https://github.com/philchalmers/SimDesign/blob/6b8fc6ee6c425f86349c4f4b53f12be0f19946e0/R/SimCollect.R#L177-L184

It looks like `readRDS()` is storing the data somewhere in RAM even though `tmp` is being overwritten. Running `gc()` doesn't seem to have let me reclaimed RAM... Any way I could free up my RAM without restarting the R session?

![image](https://github.com/user-attachments/assets/9793fa13-4c93-4a6e-b1df-60284b7aa339)

**Comment by philchalmers** [comment]
Those are very large save files. The only thing I can think to do is something like 

```r
gc <- TRUE
for(i in 1:length(filenames)){ 
     if(i %in% print_when) cat(".") 
     tmp <- try(readRDS(filenames[i]), TRUE) 
     if(is(tmp, 'try-error')) 
         stop(c('Could not read file ', filenames[i])) 
     readin[[i]] <- subset_results(tmp, select=select) 
    if(gc){
       rm(tmp)
       gc()
    }
 } 
```

Perhaps even with a `gc(full=TRUE)` to really clear the memory.

**Comment by emstruong** [comment]
Yes... Each one is ~ 8 mb compressed, and ~ 100 mb when read in. 

Isn't `full = TRUE` the default argument for `gc()` though?

**Comment by philchalmers** [comment]
> Yes... Each one is ~ 8 mb compressed, and ~ 100 mb when read in.
> 
> Isn't `full = TRUE` the default argument for `gc()` though?

Indeed, that must be a newer addition as a few years back I believe it used to be FALSE.

**Comment by emstruong** [comment]
Well, fwiw, running `gc(full = TRUE)` didn't release any of my system RAM, so I don't know what's lurking there.

**Comment by emstruong** [comment]
Does this tell you anything interesting? 
![image](https://github.com/user-attachments/assets/60471564-f4eb-4f32-ad5d-85dae9af4738)

**Comment by philchalmers** [comment]
Depends on how much you're reading in. If you have 100+ conditions then the `readin` object is going to grow very large. You may have to use the `select` argument to read in the information in batches.

**Comment by philchalmers** [comment]
Added all I can do here. I think you're just in a memory constrain issue, or you have some floating objects in your workspace that should be removed.

**Comment by emstruong** [comment]
What I'm also curious is whether this has to do with Linux's memory management or R's memory management. 

I emailed you 2 RDS files... There are a lot of warning messages and etc, but I'm pretty sure they should all be the same.

**Comment by philchalmers** [comment]
Should be patched now, there were some unnecessary objects accompanying the `check.only` option that could have been set to NULL to save more space.
