### ISSUE TITLE
`SimCollect()` and `subset_results()` fails when selecting 'errors' and 'warnings'

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#52]
SimCollect

https://github.com/philchalmers/SimDesign/blob/97b4a4f1f28aa79ceb51b1d27b46d217ab27567e/R/SimCollect.R#L187-L197

uses
https://github.com/philchalmers/SimDesign/blob/97b4a4f1f28aa79ceb51b1d27b46d217ab27567e/R/SimCollect.R#L349-L363

Perhaps using `SimExtract()` instead of `subset_results()` would be better? It seems like duplicate functionality? 

Either way, it doesn't seem like `SimCollect()` with `select = 'errors'` works because of how `subset_results` uses `dplyr` to select an `error` column. So presumably, it'll also not work with `select = 'warnings'`.

**Comment by emstruong** [comment]
I'm going to guess that part of the issue is that `subset_results()` relies on the downstream output of `Analyze()` and thus assumes that `Analyze()` returns a single row data.frame/vector and not a data frame with more than one row.

If true, then perhaps a call graph of functions/methods related to the `Analyze` output would be helpful for making sure that every function supports a data frame with more than one row

**Comment by emstruong** [comment]
Here's a temporary workaround using the debugger -- run this before `subset_results()` is called

```r
for (i in 1:length(filenames)) {
    if (i %in% print_when)
      cat(".")
    tmp <- try(readRDS(filenames[i]), TRUE)
    if (is(tmp, "try-error"))
      stop(c("Could not read file ", filenames[i]))
    readin[[i]] <- SimDesign::SimExtract(tmp, what = 'errors')
    if (gc) {
      rm(tmp)
      gc()
    }
  }
  
  errors_manual <<- readin
```

**Comment by philchalmers** [comment]
> I'm going to guess that part of the issue is that `subset_results()` relies on the downstream output of `Analyze()` and thus assumes that `Analyze()` returns a single row data.frame/vector and not a data frame with more than one row.
> 
> If true, then perhaps a call graph of functions/methods related to the `Analyze` output would be helpful for making sure that every function supports a data frame with more than one row

This shouldn't be true as subsetting is done based on the names of the elements, not based on whether a tibble/data.frame is supplied. I do however see the use of taking subsets simply to inspect errors or warning messages in larger simulations, so I think about adding support for that. Think you can make a workable reprex to save some time?

**Comment by emstruong** [comment]
Er... Would you like a RDS that has an error on a single replication result? This problem has been de-contextualized from my memory
