### ISSUE TITLE
[Feature Request] Safety Handles on Column Names? 

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#53]
Perhaps we could have checks to make sure that the user's Generate, Analyze and Summarise functions are not creating names or column names that SimDesign is using?

For example, it seems like `SimCollect()` is looking for column names that have the pattern `ERROR` and `WARNINGS`, so if the user happened to use these column names in their output--this might not be good. 

Not that I did this, but I can see something like this happening and it might already be happening with some other reserved name.

----
Edit: A fast fix would be to put warnings whenever the user's Generate/Analyze/Summarise functions give a column name that is in all caps, as it seems that most of the SimDesign's added columns are in all-caps.  Though this may be a little tricky if the user's all-caps column name appears stochastically and/or in only certain job array numbers/design-IDs.

**Comment by philchalmers** [comment]
Agreed, design-wise  `summarise()` shouldn't return keywords like ERRORS and WARNINGS, though there's nothing wrong with `Analyse()` returning such results. In fact, if `summarise()` did return those names an error would be raised, which is already the correct behaviour, but should be documented better. E.g.,

```r
library(SimDesign)

Design <- createDesign(factor1 = 1:3)

#-------------------------------------------------------------------

Generate <- function(condition, fixed_objects) {
	dat <- data.frame(1)
	dat
}

Analyse <- function(condition, dat, fixed_objects) {
	ret <- c(x=1, ERRORS=2)
	if(runif(1) < .1) stop('Error raised')
	ret
}

Summarise <- function(condition, results, fixed_objects) {
	ret <- 42
	ret
}

#-------------------------------------------------------------------

# runs fine
res <- runSimulation(design=Design, replications=100, generate=Generate, 
					 analyse=Analyse, summarise=Summarise)
res
SimResults(res)

#-------------------------------------------------------------------

Summarise2 <- function(condition, results, fixed_objects) {
	ret <- c(x=1, ERRORS=42)
	ret
}

# error
res <- runSimulation(design=Design, replications=100, generate=Generate, 
					 analyse=Analyse, summarise=Summarise2)

```
