### ISSUE TITLE
Unstated R 4.1.0 dependency

### ISSUE THREAD

**Issue by netique** [philchalmers/SimDesign#54]
The package `DESCRIPTION` says `Depends: R (>= 3.5.0)`, but in the source code, you use R 4.1.0 syntax as the lambda shorthand for function definition `\(x) ...`.

**Comment by philchalmers** [comment]
This is true. Strange the R CMD check didn't pick this up on the latest release.

**Comment by netique** [comment]
It seems the same with mirt.

**Comment by philchalmers** [comment]
This might be worth contacting the R-devel folks about as this is likely causing breakages across several packages.

**Comment by netique** [comment]
Thanks, @philchalmers, I've just posted it on r-devel mailing list.
