### ISSUE TITLE
Unable to save generated datasets when using saved seeds

### ISSUE THREAD

**Issue by stonegold546** [philchalmers/SimDesign#6]
Hello,

I am trying to replicate simulation conditions using the saved seeds.

When I set `save_seeds = TRUE` and I choose a `save_seeds_dirname`, everything works fine.

However, I am only able to load the seed if it is in the first seed directory: `SimDesign-seeds_james-Oryx-Pro` without `_4`. So to load the seeds, I had to rename the seed directory from `SimDesign-seeds_james-Oryx-Pro_4` to `SimDesign-seeds_james-Oryx-Pro`.

I could not specify this option: `load_seed = "./SimDesign-seeds_james-Oryx-Pro_4/design-row-1/seed-639"`. I had to rename the directory, then delete the directory name in the `load_seed` argument. This is a minor issue.

The major problem is I am unable to save the generated data when using the loaded seed. I obtain results, but the generated dataset is not saved. It only saves if I comment the `load_seed = "design-row-1/seed-639",` line out.

This is my script below.

```R
library(SimDesign)

inv.logit <- function(x) 1 / (1 + exp(-x))

design_4 <- expand.grid(n = 100)

generate_4 <- function(condition, fixed_objects = NULL) {
  dat <- with(condition, {
    x <- c(rnorm(n - .05 * n), rcauchy(.05 * n))
    dat <- data.frame(
      x = x, y = rbinom(n, 1, inv.logit(x * log(1.5))))
  })
  dat
}

analyze_4 <- function(condition, dat, fixed_objects = NULL) {
  ols.0 <- glm(y ~ x, gaussian, dat)

  ols.rd <- bias(unname(ols.0$coefficients[2]), .1, TRUE)
  stat <- c(ols.rd = ols.rd)
  stat
}

summaries_4 <- function(condition, results, fixed_objects = NULL) {
  ret <- colMeans(results)
  ret
}

results_4 <- runSimulation(
  design = design_4, replications = 10000, parallel = TRUE, save_seeds = TRUE,
  generate = generate_4, analyse = analyze_4, summarise = summaries_4, edit = "none",
  save = TRUE, save_results = TRUE, save_generate_data = FALSE, progress = TRUE,
  filename = "./simdata_4", seed = c(100),
  save_details = list(save_seeds_dirname = "./SimDesign-seeds_james-Oryx-Pro_4"))

results_4 <- readRDS("simdata_4.rds")

# Generated dataset does not save.
results_4_r <- runSimulation(
  design = design_4, replications = 1, seed = c(100), edit = "none",
  generate = generate_4, analyse = analyze_4, summarise = summaries_4,
  save = TRUE, save_results = FALSE, save_generate_data = TRUE, progress = TRUE,
  load_seed = "design-row-1/seed-639",
  filename = "./simdata_4r", save_details = list(
    save_generate_data_dirname = "./SimDesign-generate-data_james-Oryx-Pro_4r/")
)
```

Thank you very much

**Comment by philchalmers** [comment]
Interesting, I did not think about saving datasets given a particular seed. This option was mainly included for debugging reasons, whereby a given seed is supplied and the `edit = 'analyse'` flag were trigged, for example. Is there some reason you wish to save the data and not simply invoke the `debugging` mode? The former minor problem seems like an issue I should track down, so thanks for the report.

**Comment by stonegold546** [comment]
I was interested in pulling out datasets that meet specific criteria for demonstration purposes. But this is fine. Right now, I figure I can write a dataset to the hard drive right after creating it if it meets my criteria(?) I've never attempted to use the `edit` option, so it's useful to know there's that option.
Thanks very much!

**Comment by philchalmers** [comment]
I'm actually not able to replicate you issue. I ran your provided code, though changed the `load_seed = "design-row-1/seed-639",` portion to something I saved, such as `load_seed = "design-row-1/seed-5",`, and it worked fine. Though I'm getting a lot of error messages popping up, so something might be a little unclean in the example. Could you perhaps simplify the example to make it work in a new session? Thanks.

**Comment by stonegold546** [comment]
I see why this happened. I updated to the GitHub version and the arguments for the `bias()` function have changed. I've updated the most recent snippet to reflect this.

**Comment by philchalmers** [comment]
Thanks, got it working. I see that I [disabled this behaviour explicitly](https://github.com/philchalmers/SimDesign/blob/e3623db5e54709babef0af31f107fe93d866a4cc/R/runSimulation.R#L785) so that datasets and results weren't accidentally overwritten when providing a seed (because at that points is kind of redundant) . However, given that the documentation now basically says "never save your generated data and only rarely save your analysis results if your hard-drive can hold it", I don't see why this should be disabled when passing a particular seed. 

I'll push this results in a moment. Cheers.

**Comment by stonegold546** [comment]
It now works as expected. Thanks very much!
