### ISSUE TITLE
Infinite loop triggered by error at analyse= return

### ISSUE THREAD

**Issue by oguzhanogreden** [philchalmers/SimDesign#7]
I stumbled upon a way to trigger an infinite loop. I must say this was a result of disregarding a detail in the examples. I'm opening an issue since I think this was a reasonable disregard.

The infinite loop can be triggered like this:
```
analyse <- function(condition, dat, fixed_objects = NULL) {
  analysis_1 <- mean(rnorm(100))

  list(a1 = analisis_1) # mind the typo...
}
```

I believe this is a common way of returning functions, although the examples first create an object and return that.

**Comment by philchalmers** [comment]
I used this to try to reproduce this issue:

```r
library(SimDesign)

design <- expand.grid(n = 100)

generate <- function(condition, fixed_objects = NULL) {
    rnorm(condition$n)
}

analyze <- function(condition, dat, fixed_objects = NULL) {
    analysis_1 <- mean(dat)
    
    list(a1 = analisis_1) # mind the typo...
}

summaries <- function(condition, results, fixed_objects = NULL) {
    ret <- bias(results, 0)
    ret
}

results <- runSimulation(
    design = design, replications = 1000, 
    generate = generate, analyse = analyze, summarise = summaries)
```

But the output I get is what was expected:

```
 Error: Row 1 in design was terminated because it had 50 consecutive errors. 

Last error message was: 

  object 'analisis_1' not found 
```

**Comment by oguzhanogreden** [comment]
Indeed, I should have tested it with a simple case. I assumed a fresh session would suffice.

I still can reproduce the behavior on my side, I'll track this down and report back!
