### ISSUE TITLE
Computing relative bias when population parameter is a vector rather than scalar.

### ISSUE THREAD

**Issue by stonegold546** [philchalmers/SimDesign#9]
I had problems computing the relative bias using the `bias()` function when the population parameter is a vector.

Looking at the code for `bias()`, it appears bias is first computed as a scalar, mean(estimate(i) - parameter(i)). If the user sets the option, `type = "relative"`, this scalar is then divided by the parameter vector which results in a vector of results instead of a scalar for relative bias.

I do not know if this is clear, but mathematically, `bias()` appears to be doing mean(bias(i)) / parameter(i) resulting in a vector of length i, when I think it should be doing: mean(bias(i)/parameter(i)) resulting in a scalar.

Thinking about it some more, maybe we should divide by the absolute value of the parameter instead?

Reproducible example

```r
set.seed(1); n <- 5

par <- rnorm(n)
est <- par + .05 * rnorm(n)

SimDesign::bias(est, par, type = "relative")
[1] -0.010785765  0.036792970 -0.008085869  0.004235482  0.020505687

mean(est - par) / (par)
[1] -0.010785765  0.036792970 -0.008085869  0.004235482  0.020505687

# I can take the mean to produce a scalar but
mean(SimDesign::bias(est, par, type = "relative"))
[1] 0.008532501

# Using the SimDesign approach but if I divide by the absolute value instead,
mean(mean(est - par) / abs(par))
[1] 0.01608115

# This is what I think I want:
mean((est - par) / abs(par))
[1] 0.01662195
```

Which approach of the three is preferable?

Thanks.

**Comment by philchalmers** [comment]
I don't see an easy way to do this, because the denominator term is absoulate rather than in the sign of the original. I've added a type 'abs_relative' to do this now, which should help your position. Here's what I get from the following dev version:

```r
SimDesign::bias(est, par, type = "abs_relative")
[1] 0.01662195
```

You could even stack with with the `abs` input to take the absolute value of the numerator difference terms first, like so:

```r
SimDesign::bias(est, par, type = "abs_relative", abs=TRUE)
[1] 0.06135205
```

Which is effectively computing `mean(abs(est - par) / abs(par))`. HTH.

**Comment by stonegold546** [comment]
Thanks very much!
